### ISSUE TITLE
Hilti 2022 score

### ISSUE THREAD

**Issue by jaehyuck0103** [smartroboticslab/okvis2#9]
Hello.
Firstly, thank you for sharing good project.

okvis2 marks high scores on the Hilti 2022 leaderboard, so I also tried to submit the okvis2 result to the leaderboard.
I tested only exp01, and while the trajectory is completed, the score is very low.
(your leaderboard score: 42.31,  hilti_challenge_2022.yaml: 0.0, hilti_challenge_2022_onlinecalib.yaml: 6.9)

I did not modify the project's default compile options and the default config.
I use `okvis_app_synchronous` app to the Hilti dataset of EuRoC format.

Did you make any changes to the GitHub version before submitting to the Hilti leaderboard?

**Comment by jaehyungjung** [comment]
Hi, thank you for your interest in OKVIS2!

I recommend you to set `do_extrinsics: true` and `do_extrinsics_final_ba: true`. As written in the paper, we find out that online cam-IMU extrinsic calibration generally gives better accuracy.

Also, please note that there are 2 trajectory outputs: `*_trajectory.csv` and `*_final_trajectory`, which are causal and non-causal outputs, respectively. The score in the leaderboard corresponds to the latter.

**Comment by jaehyuck0103** [comment]
The score has been successfully reproduced.
Thank you!
